CREATE TABLE test_new (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload TEXT
);

INSERT INTO test_new (payload)
VALUES ('PAYLOAD_4');

INSERT INTO test_new (payload)
VALUES ('PAYLOAD_2');

SELECT * FROM test_new;


CREATE TABLE IF NOT EXISTS library_units
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id  VARCHAR, -- human readable unit_id (1, 2, 3, ...)
    location VARCHAR,
    floor    VARCHAR,
    format   VARCHAR
);

CREATE TABLE IF NOT EXISTS inbounded_articles (
	ql VARCHAR PRIMARY KEY,
	simple_sku VARCHAR,
	config_sku VARCHAR,
	ean VARCHAR,
	name VARCHAR,
	location VARCHAR,
	floor VARCHAR,
	unit_id VARCHAR,
	is_in_library BOOLEAN NOT NULL DEFAULT FALSE,
	is_outbounded BOOLEAN NOT NULL DEFAULT FALSE,
	is_lost BOOLEAN NOT NULL DEFAULT FALSE,
	brand VARCHAR,
	color VARCHAR,
	gender VARCHAR,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    library_units_id INT REFERENCES library_units (id)
);


CREATE TABLE IF NOT EXISTS stargate_events (
                                               id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               campaign_id TEXT NOT NULL,
                                               name TEXT,
                                               retail_event_id TEXT
);

CREATE INDEX CONCURRENTLY IF NOT EXISTS sg_ev_cmp_id_idx ON stargate_events(campaign_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS sg_ev_ret_id_idx ON stargate_events(retail_event_id);

-- 	PRIMARY KEY (id, location, floor)